#!/usr/bin/env bash

## Kill if already running
killall -9 xfsettingsd picom polybar dunst xfce4-power-manager

## xfce4-settings daemon
xfsettingsd &

## Restore Wallpaper
nippy-wal --restore &

## Enable power management
xfce4-power-manager &

## Start Compositing Manager
exec nippy-compositor start &

## Launch Polybar or Tint2
exec polybar -r &

## Notification Daemon
exec dunst &

## Launch Plank
exec plank &

## Thunar Daemon
exec thunar --daemon &

## These applets are specifically for tint2 panel.
## If you're using tint2 as panel, Uncomment these applets.

## User Friendly Network Menu
nm-applet --indicator &

## User Friendly Bluetooth Menu
blueman-applet &

nippy-clippy daemon &
